export const CARE_RECOMMENDATIONS = [
  'Bright direct light',
  'Bright indirect light',
  'Low light is fine',
  'Water weekly',
  'Water every 2 weeks',
  'Water when the top inch of soil is dry',
  'Let the soil dry out between waterings',
  'Keep the soil evenly moist',
  'Water less in winter',
  'Mist the leaves regularly',
  'Prefers high humidity',
  'Well-draining soil',
  'Use a pot with drainage holes',
  'Fertilize monthly in spring and summer',
  'Wipe the leaves to remove dust',
  'Rotate the pot for even growth',
  'Prune dead or yellow leaves',
  'Repot every 1 to 2 years',
  'Keep away from cold drafts',
  'Keep away from heaters and vents',
  'Toxic to pets, keep out of reach',
]
