export const PLANT_TYPES = [
  'African Violet',
  'Aloe Vera',
  'Areca Palm',
  'Boston Fern',
  'Bird of Paradise',
  'Cast Iron Plant',
  'Chinese Evergreen',
  'Christmas Cactus',
  'Croton',
  'Dracaena',
  'Dumb Cane',
  'English Ivy',
  'Fiddle Leaf Fig',
  'Jade Plant',
  'Kentia Palm',
  'Lucky Bamboo',
  'Maidenhair Fern',
  'Monstera',
  'Orchid',
  'Parlor Palm',
  'Peace Lily',
  'Peperomia',
  'Philodendron',
  'Pilea',
  'Pothos',
  'Prayer Plant',
  'Rubber Plant',
  'Snake Plant',
  'Spider Plant',
  'String of Pearls',
  'Succulent',
  'Swiss Cheese Plant',
  'Umbrella Plant',
  'Weeping Fig',
  'ZZ Plant',
]
