const INDOOR_FOLIAGE = [
  'Aloe Vera',
  'Areca Palm',
  'Bird of Paradise',
  'Boston Fern',
  'Calathea',
  'Cast Iron Plant',
  'Chinese Evergreen',
  'Coleus',
  'Croton',
  'Dracaena',
  'Dumb Cane',
  'English Ivy',
  'Fiddle Leaf Fig',
  'Hoya',
  'Kentia Palm',
  'Lucky Bamboo',
  'Maidenhair Fern',
  'Monstera',
  'Nerve Plant',
  'Parlor Palm',
  'Peperomia',
  'Philodendron',
  'Pilea',
  'Polka Dot Plant',
  'Pothos',
  'Prayer Plant',
  'Rubber Plant',
  'Snake Plant',
  'Spider Plant',
  'Staghorn Fern',
  'Swiss Cheese Plant',
  'Umbrella Plant',
  'Weeping Fig',
  'ZZ Plant',
]

const SUCCULENTS_AND_CACTI = [
  'Barrel Cactus',
  'Burro\'s Tail',
  'Christmas Cactus',
  'Easter Cactus',
  'Echeveria',
  'Haworthia',
  'Jade Plant',
  'Kalanchoe',
  'Lithops',
  'Moon Cactus',
  'Old Man Cactus',
  'Panda Plant',
  'Prickly Pear',
  'Sedum',
  'String of Pearls',
  'Succulent',
  'Thanksgiving Cactus',
]

const FLOWERING_INDOOR = [
  'African Violet',
  'Amaryllis',
  'Anthurium',
  'Begonia',
  'Bromeliad',
  'Cyclamen',
  'Flamingo Flower',
  'Gardenia',
  'Gloxinia',
  'Hibiscus',
  'Jasmine',
  'Moth Orchid',
  'Orchid',
  'Peace Lily',
  'Poinsettia',
  'Streptocarpus',
  'Wax Plant',
  'Zygocactus',
]

const GARDEN_FLOWERS = [
  'Alstroemeria',
  'Anemone',
  'Aster',
  'Azalea',
  'Bleeding Heart',
  'Bougainvillea',
  'Camellia',
  'Carnation',
  'Chrysanthemum',
  'Clematis',
  'Cosmos',
  'Dahlia',
  'Daffodil',
  'Daisy',
  'Daylily',
  'Delphinium',
  'Fuchsia',
  'Geranium',
  'Gerbera Daisy',
  'Gladiolus',
  'Hyacinth',
  'Hydrangea',
  'Iris',
  'Lavender',
  'Lily',
  'Lisianthus',
  'Marigold',
  'Morning Glory',
  'Pansy',
  'Peony',
  'Petunia',
  'Primrose',
  'Ranunculus',
  'Rose',
  'Snapdragon',
  'Sunflower',
  'Sweet Pea',
  'Tulip',
  'Verbena',
  'Violet',
  'Zinnia',
]

const ORNAMENTAL_SHRUBS_AND_TREES = [
  'Bamboo Palm',
  'Bonsai',
  'Ficus Benjamina',
  'Frangipani',
  'Ixora',
  'Japanese Maple',
  'Lantana',
  'Lemon Tree',
  'Money Tree',
  'Norfolk Island Pine',
  'Oleander',
  'Ponytail Palm',
  'Sago Palm',
  'Schefflera',
  'Yucca',
]

// Sorted and de-duplicated, so the list stays easy to scan as it grows.
export const PLANT_TYPES = [...new Set([
  ...INDOOR_FOLIAGE,
  ...SUCCULENTS_AND_CACTI,
  ...FLOWERING_INDOOR,
  ...GARDEN_FLOWERS,
  ...ORNAMENTAL_SHRUBS_AND_TREES,
])].sort((a, b) => a.localeCompare(b))
